add-controllers 1 rev.
YakovMorkovkin/java-shareit pull request #1
Opened 2023-02-07 09:46 UTC by YakovMorkovkin

2023-02-08 06:48 UTC, krylov-sergey-sergeevich requested changes
Привет. В целом неплохо, давай проработаем исключения и по пути чекстайл поправим, а то иногда он едет. Исключения надо везде поправить, а не только где отметил, тк я решил не спамить.

2023-02-08 06:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private long id;
**Можно лучше:** `private Long id;`

2023-02-08 06:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private long id;
**Можно лучше:** `private Long id;`

2023-02-08 06:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                () -> new NotFoundException("User with id -" + userId + " not found"));
Давай создадим специальное исключение UserFoundException наследника NotFoundException и сделаем так чтобы каждый раз не повторять текст:
`() -> new UserFoundException(userId));`

2023-02-08 06:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +                () -> new NotFoundException("User with id -" + userId + " isn't found")
UserFoundException

2023-02-08 06:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/dao/UserRepositoryImpl.java
> +            throw new EmailDuplicateException("User with email - " + user.getEmail() + " already exists");
Хочу чтобы тут не нужно было писать весь текст исключения и это было сделано через правильное использование конструктора исключения.

2023-02-08 06:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +public class UserDto implements Serializable {
лишние пробелы присутствуют

2023-02-09 05:25 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private long id;
поправил

2023-02-09 05:25 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private long id;
поправил

2023-02-09 06:13 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                () -> new NotFoundException("User with id -" + userId + " not found"));
сделал

2023-02-09 06:21 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +                () -> new NotFoundException("User with id -" + userId + " isn't found")
сделал

2023-02-09 06:21 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/user/dao/UserRepositoryImpl.java
> +            throw new EmailDuplicateException("User with email - " + user.getEmail() + " already exists");
сделал

2023-02-09 06:22 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +public class UserDto implements Serializable {
поправил

2023-02-10 07:14 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-02-10 09:15 UTC, merged