add-bookings
YakovMorkovkin/java-shareit pull request #2
Opened 2023-02-23 06:19 UTC by YakovMorkovkin

2023-02-24 18:00 UTC, krylov-sergey-sergeevich requested changes
Привет, работа неплохая, но есть над чем поработать:

1) Почему то отсутствует Service слой почти, нужно его добавить и вынести туда базовые сценарии получения и т/д элементов. Это так-же должно помочь избежать дублирования кода.
2) Можно лучше: JsonFormat - можно почитать и докинуть для дат
3) С исключениями надо проверить что все корректны

Буду ждать с правками =)

2023-02-24 18:00 UTC, krylov-sergey-sergeevich commented on pom.xml
> +
лишние строки

2023-02-24 18:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                 @NotEmpty @RequestHeader("X-Sharer-User-Id") Long userId) {
"X-Sharer-User-Id" - давай вынесем в класс Constants

2023-02-24 18:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        userRepository.findById(userId).orElseThrow(() -> new UserFoundException(userId));
UserFoundException - звучит странно исключение, в название не озвучена проблема

2023-02-24 18:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        userRepository.findById(userId).orElseThrow(() -> new UserFoundException(userId));
А почему не вынесем это в полнеценный метод сервисного слоя

2023-02-24 18:00 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            throw new NotFoundException("Owner can't booking own item");
NotFoundException - точно название исключения подходит под суть темы исключения?

2023-02-24 18:00 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    PRIMARY KEY (id),
CONSTRAINT pk_users PRIMARY KEY (id), - рекомендую все констрейнты вот так оформлять

2023-02-24 18:00 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    PRIMARY KEY (id),
Это тоже констрейнт который следует оформлять как выше указал

2023-02-25 11:52 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        userRepository.findById(userId).orElseThrow(() -> new UserFoundException(userId));
Поправил

2023-02-25 11:53 UTC, YakovMorkovkin commented on pom.xml
> +
поправил

2023-02-25 11:59 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            throw new NotFoundException("Owner can't booking own item");
поправил

2023-02-25 12:22 UTC, YakovMorkovkin commented on src/main/resources/schema.sql
> +    PRIMARY KEY (id),
поправил

2023-02-25 12:22 UTC, YakovMorkovkin commented on src/main/resources/schema.sql
> +    PRIMARY KEY (id),
поправил

2023-02-25 13:06 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                 @NotEmpty @RequestHeader("X-Sharer-User-Id") Long userId) {
сделал

2023-02-25 14:34 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        userRepository.findById(userId).orElseThrow(() -> new UserFoundException(userId));
сделал

2023-02-26 06:42 UTC, krylov-sergey-sergeevich requested changes
Привет

Вижу хорошие изменения, осталось докрутить момент с исключениями и будет отлично =)

2023-02-26 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new NotFoundException("User isn't owner any item");
Точно такое название исключения тут подойдет? Может UserNotHaveItemBusinessException(userId) ( или по другому, но суть ясна)

2023-02-26 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Start date of booking after end date");
Мы не кидаем спринговые исключения - это плохая практика особенно когда по сути у нас валидация не прошла, нужно сделать свое исключение

2023-02-26 06:42 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Booking with id-" + booking.getId()
Мы не кидаем сприговые ислючения

2023-02-26 07:18 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Booking with id-" + booking.getId()
поправил

2023-02-26 07:26 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Start date of booking after end date");
сделал

2023-02-26 07:33 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new NotFoundException("User isn't owner any item");
поправил

2023-02-27 06:09 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-02-27 06:45 UTC, merged