add-item-requests 1 rev.
YakovMorkovkin/java-shareit pull request #3
Opened 2023-03-14 16:54 UTC by YakovMorkovkin

2023-03-17 19:06 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом неплохо

- Лично я бы объеденил бы переменные Integer offset, Integer limit в один объект и везде бы его в параметрах принимал бы, вместо двух - так было бы короче, но это как хочешь
- Логов маловато
- На счет тестов тут трудно критиковать тк сколько людей столько и вариантов написания тестов (вот мой опыт говорит так) и поэтому главное чтобы они проверяли что должны, а их качество это субьективщина полная, в целом я бы просто рекомендовал бы объекты для тестов билдить как то отдельно в специальных фабриках чтоли , но опять же это придирки

Буду ждать с правками и будет зачет =)

2023-03-17 19:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new StartEndMismatchException();
Прекрасное исключение, но нет подробностей для кого чего оно кидается

2023-03-17 19:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    List<ItemShortDto> items;
модификатор доступа

2023-03-17 19:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +@Service
аннотация тут не нужна

2023-03-19 07:34 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    List<ItemShortDto> items;
поправил

2023-03-19 07:34 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +@Service
поправил

2023-03-19 07:34 UTC, YakovMorkovkin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new StartEndMismatchException();
поправил

2023-03-19 08:03 UTC, YakovMorkovkin commented
логов добавил (пользовался ими при отладке и потом удалил зачем-то, видать заработался)

2023-03-20 06:27 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки, вижу что пункт 1 не сделан, но это не критично - зачет!

2023-03-20 14:48 UTC, merged