add-docker 1 rev.
YakovMorkovkin/java-shareit pull request #4
Opened 2023-03-23 17:41 UTC by YakovMorkovkin

2023-03-24 08:19 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом все хорошо вроде как, есть один вопрос давай после него еще раз гляну и зачет будет.

2023-03-24 08:19 UTC, krylov-sergey-sergeevich commented on gateway/Dockerfile
> +ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
Для чего эти параметры передаем?

2023-03-24 08:19 UTC, krylov-sergey-sergeevich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<Object> getBookingById(@RequestHeader("X-Sharer-User-Id") long userId,
"X-Sharer-User-Id" эта штука много где повторяется рекомендую ее вынести в класс Constants и использовать переменную

2023-03-24 12:39 UTC, YakovMorkovkin commented on gateway/Dockerfile
> +ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
Для подключения к контейнеру для отладки

2023-03-24 12:39 UTC, YakovMorkovkin commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<Object> getBookingById(@RequestHeader("X-Sharer-User-Id") long userId,
Поправил

2023-03-25 07:38 UTC, krylov-sergey-sergeevich approved these changes
Привет, зачет

2023-04-13 18:26 UTC, merged